modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${license}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "icon.png"
credits = "${credits}"
authors = "${mod_author}"
description = '''${description}'''
[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "balm"
type = "required"
versionRange = "${balm_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "hbs_foundation"
type = "required"
versionRange = "[${foundation_version_min},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "createbigcannons"
type = "required"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "hbs_satellites"
type = "required"
versionRange = "[0,)"
ordering = "BEFORE"
side = "BOTH"
